apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcp
  template:
    metadata:
      labels:
        app: gcp
    spec:
      containers:
      - name: gcp-devops-gke
        image: gcr.io/turing-seeker-461812-r5/gke-pj
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: "gcp-devops-gke-service"
  namespace: "gke-deploy-dev"
  labels:
    app.kubernetes.io/managed-by: "gcp-cloud-build-deploy"
spec:
  type: LoadBalancer
  selector:
    app: "gcp"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80  # changed from 5000 to 80